name: Pull Request

on:
  workflow_call:
    inputs:
      python-version-unit:
        required: true
        description: "Python version"
        type: string
        default: "['3.8', '3.10']"
      python-version-func:
        required: true
        description: "Python version"
        type: string
        default: "3.10"
      tox-version:
        required: false
        description: |
          Tox version, which should be used, e.g. `<4`. If not specified, the
          latest version of tox will be installed.
        type: string
        default: ""
      working-directory:
        required: false
        description: "To change working directory"
        type: string
        default: "."
      snapcraft:
        required: false
        description: |
          Flag if snap is tested. If set to true, snapcraft will be installed.
        type: boolean
        default: false
      timeout-minutes:
        required: false
        description: "Configurable timeout limit for functional test job"
        type: number
        default: 60
      commands:
        required: true
        description: "Command to run functional tests with"
        type: string
      juju-channel:
        required: false
        type: string
        default: "2.9/stable"
      # actions-operator
      provider:
        required: false
        type: string
        default: "lxd"
      nested-containers:
        required: false
        type: boolean
        default: false

jobs:
  lint-unit:
    name: Lint checkers and unit tests
    uses: ./.github/workflows/_lint-unit.yaml
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version-unit }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}

  func:
    uses: ./.github/workflows/_func.yaml
    needs: 
    - lint-unit
    secrets: inherit
    with:
      python-version: ${{ inputs.python-version-func }}
      tox-version: ${{ inputs.tox-version }}
      working-directory: ${{ inputs.working-directory }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
      snapcraft: ${{ inputs.snapcraft }}
      commands: ${{ inputs.commands }}
      provider: ${{ inputs.provider }}
      nested-containers: ${{ inputs.nested-containers }}
      juju-channel: ${{ inputs.juju-channel }}
